import { Noto_Sans } from "next/font/google";

const notoSans = Noto_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // or whatever weights you need
  variable: "--font-noto-sans",
});
export const metadata = {
  title: "Professco",
  description: "Generated by create next app",
};

import "@/app/_styles/globals.css";
import { ContextProvider } from "@/app/_utils/Contexts";
import HomeNav from "@/app/_components/HomeNav/HomeNav";
import { Providers } from "@/app/_components/Providers";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${notoSans.variable}`}>
        <Providers>
          <ContextProvider>
            <HomeNav />
            {children}
          </ContextProvider>
        </Providers>
      </body>
    </html>
  );
}
